model:
  base_learning_rate: 4.5e-06
  target: stablediffusion.ldmmodels.autoencoder.AutoencoderKL
  params:
    monitor: val/rec_loss
    embed_dim: 16
    lossconfig:
      target: stablediffusion.ldmmodules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 50001
        kl_weight: 1.0e-06
        disc_weight: 0.5
    ddconfig:
      double_z: true
      z_channels: 16
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 16
      dropout: 0.0
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 6
    wrap: true
    train:
      target: stablediffusion.ldmdata.openimages.FullOpenImagesTrain
      params:
        size: 384
        crop_size: 256
    validation:
      target: stablediffusion.ldmdata.openimages.FullOpenImagesValidation
      params:
        size: 384
        crop_size: 256
